name: Experimento Ship of Harkinian Universal

on:
  workflow_dispatch:
  push:
    branches: [experimento-soh-universal]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup and build the project
        run: |
          cd docker
          make setup
          make build_release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soh-universal-apk
          path: |
            Android/app/build/outputs/apk/release/*.apk
